### ISSUE TITLE
Tour de nbpresent: screenplay

### ISSUE THREAD

**Issue by bollwyvl** [ContinuumIO/nbpresent#3]
Use [bootstrap tour](http://bootstraptour.com/) to walk through the key functionality of nbpresent.

Here's the [notebook tour](https://github.com/jupyter/notebook/blob/6d6d59779a515d624029de9ab1369dba3391e1f0/notebook/static/notebook/js/tour.js).

One approach would just be to start with the content/data screenplay, and build up a `src/yml/tour.yml` with the text and order of steps. I might have to do some work to get the selectors to all work, so it might be a sec before we start thinking about clicking buttons, etc: we can add the `onShow` later. At that point, we can basically do a self-building presentation.

There are some other UI things to think about as well, which might as well be discussed here:
- does the tour show up unbidden the first time?
- how do i hide it forever?
- how do i get it back after hiding it forever?
- do we want to integrate the functionality into the slides themselves: do baobab stuff on `onShow`

@tonyfast

**Comment by bollwyvl** [comment]
The base story of this is in as of #5 (pushed to pip).

There are a ton of other ways the tour could go, still interested in the big story arc of "why," perhaps.

**Comment by damianavila** [comment]
That's really nice from the user perspective... do you want to still have this opened for further modifications?

**Comment by bollwyvl** [comment]
I wanted to keep it open because it's not done _yet_... the other PR just got the baseline stuff in place, and was written and hacked at the same time. i want to go back through with a plan, and probably build in some links, etc.

**Comment by damianavila** [comment]
That's ok, thanks for the info...

**Comment by bollwyvl** [comment]
This is pretty much in, as one can see from the [screencast](http://continuumio.github.io/nbpresent/).

I'll try to keep adding new features to the tour, and therefore the screencast, as I make them.

There may be some reorganization later!
